### ISSUE TITLE
RuntimeError: The size of tensor a (512) must match the size of tensor b (2) at non-singleton dimension 1

### ISSUE THREAD

**Issue by zhengzheng-yay** [by2101/OpenASR#13]
Traceback (most recent call last):
  File "/home/lenovo/E2E-model/OpenASR/OpenASR-master/egs/aishell2/s5/../../../src/train.py", line 134, in <module>
    trainer.train()
  File "/home/lenovo/E2E-model/OpenASR/OpenASR-master/src/trainer.py", line 152, in train
    tr_loss = self.iter_one_epoch()
  File "/home/lenovo/E2E-model/OpenASR/OpenASR-master/src/trainer.py", line 208, in iter_one_epoch
    data = next(loader_iter)
  File "/home/lenovo/anaconda3/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 345, in __next__
    data = self._next_data()
  File "/home/lenovo/anaconda3/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 856, in _next_data
    return self._process_data(data)
  File "/home/lenovo/anaconda3/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 881, in _process_data
    data.reraise()
  File "/home/lenovo/anaconda3/lib/python3.7/site-packages/torch/_utils.py", line 394, in reraise
    raise self.exc_type(msg)
RuntimeError: Caught RuntimeError in DataLoader worker process 8.
Original Traceback (most recent call last):
  File "/home/lenovo/anaconda3/lib/python3.7/site-packages/torch/utils/data/_utils/worker.py", line 178, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/lenovo/anaconda3/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 47, in fetch
    return self.collate_fn(data)
  File "/home/lenovo/E2E-model/OpenASR/OpenASR-master/src/data.py", line 242, in __call__
    padded_waveforms, wave_lengths = load_wave_batch(paths)
  File "/home/lenovo/E2E-model/OpenASR/OpenASR-master/src/data.py", line 189, in load_wave_batch
    padded_waveforms[i, :lengths[i]] += waveforms[i]
RuntimeError: The size of tensor a (512) must match the size of tensor b (2) at non-singleton dimension 1
您好，我在使用AISHELL-1数据未出先问题，使用AISHELL-2出现以上问题，搜索很多资料，问题没有得到解决，请问该怎样修改？谢谢！

**Comment by by2101** [comment]
您好，可能是aishell2的数据里面有的音频长度不对？比如为空之类的。
您可以做一个长度过滤试试。

**Comment by zhengzheng-yay** [comment]
> 您好，可能是aishell2的数据里面有的音频长度不对？比如为空之类的。 您可以做一个长度过滤试试。
确实有空音频，已解决，感谢。
