### ISSUE TITLE
Error during train.sh

### ISSUE THREAD

**Issue by panxin801** [by2101/OpenASR#4]
Hi, I am using torch==1.4.0 with cuda, when I am training model with `bash train.sh` I meet the following error:
```
Traceback (most recent call last):
35910   File "/root/OpenASR/egs/aishell1/s5/../../../src/train.py", line 131, in <module>
35911     trainer.train()
35912   File "/root/OpenASR/src/trainer.py", line 152, in train
35913     tr_loss = self.iter_one_epoch()
35914   File "/root/OpenASR/src/trainer.py", line 229, in iter_one_epoch
35915     lst_t=self.lst_t)
35916   File "/root/.local/lib/python3.7/site-packages/torch/nn/modules/module.py", line 532, in __call__
35917     result = self.forward(*input, **kwargs)
35918   File "/root/.local/lib/python3.7/site-packages/torch/nn/parallel/data_parallel.py", line 152, in forward
35919     outputs = self.parallel_apply(replicas, inputs, kwargs)
35920   File "/root/.local/lib/python3.7/site-packages/torch/nn/parallel/data_parallel.py", line 162, in parallel_apply
35921     return parallel_apply(replicas, inputs, kwargs, self.device_ids[:len(replicas)])
35922   File "/root/.local/lib/python3.7/site-packages/torch/nn/parallel/parallel_apply.py", line 85, in parallel_apply
35923     output.reraise()
35924   File "/root/.local/lib/python3.7/site-packages/torch/_utils.py", line 394, in reraise
35925     raise self.exc_type(msg)
35926 TypeError: Caught TypeError in replica 2 on device 2.
35927 Original Traceback (most recent call last):
35928   File "/root/.local/lib/python3.7/site-packages/torch/nn/parallel/parallel_apply.py", line 60, in _worker
35929     output = module(*input, **kwargs)
35930   File "/root/.local/lib/python3.7/site-packages/torch/nn/modules/module.py", line 532, in __call__
35931     result = self.forward(*input, **kwargs)
35932 TypeError: forward() missing 3 required positional arguments: 'batch_wave', 'lengths', and 'target_ids'
```
Do you know why ? If this is the mismatch between torch version ?

**Comment by by2101** [comment]
Hi, I haven't encounter this issue. my torch==1.2. I did't try higher version.
Maybe you can try with single GPU first.

**Comment by panxin801** [comment]
OK I know thank you
